@echo off
echo Building DLLs...
"D:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" --build d:/Programming/OpenAG/build --config Debug --target ALL_BUILD -j 14 --
echo Copying...
copy "D:\Programming\OpenAG\build\Debug\client.dll" "C:\HalfLifeModding\valve\cl_dlls\client.dll"
echo Launching...
start C:\HalfLifeModding\hl.exe